[profile.release]
panic = "unwind"
edition = "2021"
rust-version = "1.56"

[workspace]
members = [
    "frame/*",
    "node",
    "price-feed",
    "runtime/picasso",
	"runtime/common",
	"runtime/primitives",
	"utils/faucet-server",
	"utils/parachain-utils",
	"integration-tests",
]
