[[bin]]
name = "composable"
path = "src/main.rs"

[package]
name = "composable"
version = '1.0.9'
authors = ["Composable Developers"]
homepage = "https://composable.finance"
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
composable-node = { path = "node", features = [ "composable", "dali" ]  }
color-eyre = { version = "0.5.11", default-features = false }

[features]
runtime-benchmarks = [ "composable-node/runtime-benchmarks" ]
std = [ "composable-node/std" ]

[workspace]
members = [
    "runtime/common",
    "runtime/primitives",
    "frame/*",
    "integration-tests",
    "integration-tests/simnode",
    "node",
    "runtime/picasso",
    "runtime/dali",
    "runtime/composable",
    "utils/price-feed"
]

[profile.release]
# Polkadot runtime requires unwinding.
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
