name: Run Ansible Playbooks

on: 
  workflow_dispatch:
    branches: 
        - master
        - stable-release
  push: 
    branches:
        - master
        - stable-release

env: 
  RELEASE_VERSION: ""
  TARGET: "test_node_yes"
  PLAYBOOK: "client-upgrade.yml"
  INVENTORY_FILE: "gcp.yaml"

jobs:
  run-playbooks:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Run ansible playbook
      working-directory: "/opt/ansible/inventory"
      run: |
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^[0-9]' | tail -1)" >> $GITHUB_ENV
        ansible-playbook -l $TARGET $PLAYBOOK -i $INVENTORY_FILE -e 'ansible_python_interpreter=/usr/bin/python3'
