name: 'Testnet Deploy'
# ... 
jobs:
#...  
  deploy:
    runs-on: ubuntu-latest
    needs: build # The build job should finished successfully.
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}