name: Build Binary and Upload Artifacts
on:
  push:
    branches:
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  binary-build:
    runs-on: 
      - self-hosted
      - linux
      - x64
      - sre
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Set env
        run: echo "RELEASE_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Install toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup default stable
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Build Composable Binary
        run: |
          /home/runner/.cargo/bin/cargo build --release -p composable

      - name: Build Parachain Utils Binary
        run: |
          BUILD_PROFILE=parachain-utils make build

  package-build:
    needs: [binary-build]
    runs-on:
      - self-hosted
      - linux
      - x64
      - sre
    steps: 
      - uses: actions/checkout@v2

      - name: Package Build Release as Artifacts
        run: |
          tar -zcvf composable-{{ env.RELEASE_VERSION }}.tar.gz target/ 

  upload-artifacts:
    needs: [package-build]
    runs-on: 
      - self-hosted
      - linux
      - x64
      - sre
    steps:
      - name: Upload artifacts to Composable Artifact Registry
        run: |
          gsutil cp composable-{{ env.RELEASE_VERSION }}.tar.gz gs://composable-binaries/releases/client/{{ env.RELEASE_VERSION }}/


      