name: Build Binary and Upload Artifacts
on:
  push:
    branches:
      - 'release/**'

jobs:
  binary-build:
    runs-on: 
      - self-hosted
      - linux
      - x64
      - sre
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Set env
        run: echo "RELEASE_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Install toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup default stable
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Build Composable Binary
        run: |
          /home/runner/.cargo/bin/cargo build --release -p composable

      - name: Build Parachain Utils Binary
        run: |
          /home/runner/.cargo/bin/cargo build --release -p parachain-utils
        
      - name: Build Faucet Server Binary
        run: |
          /home/runner/.cargo/bin/cargo build --release -p faucet-server

      - name: Package Build Release as Artifacts
        run: |
          zip -r target.zip target/

      - name: Upload artifacts to Composable Artifact Registry
        run: |
          gsutil cp target.zip  gs://composable-binaries/releases/client/v0.1.0/


