name: "Build Artifacts"

on:
  workflow_dispatch:
  push: 
    tags: 
      - '*'
      
env:
  DOCKER_USER_OPTION: '$UID:$GID'
  SCCACHE_GCS_BUCKET: 'composable-build-artefacts'
  RUSTC_WRAPPER: "/home/runner/.cargo/bin/sccache"
  SCCACHE_GCS_RW_MODE: "READ_WRITE"

jobs:
  build-and-publish:
    runs-on: 
        - self-hosted
        - linux
        - x64
        - sre
    strategy: 
      fail-fast: true

    steps:
    - name: cleanup 
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
  
    - name: Set env
      run: |
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1 )" >> $GITHUB_ENV
        make version

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: 🔨 Build and Upload Composable Binary
      #working-directory: "./.maintain/"
      id: client_release
      run: |
        .maintain/client_release.sh

    - name: Build wasm with srtool
      #working-directory: "./.maintain/"
      id: runtime_release
      run: |
        .maintain/runtime_release.sh
    
    - name: ListBuildOuput
      run: |
        ls
    
    
