name: "Build Artifacts"

on:
  workflow_dispatch:
  push: 
    tags: 
      - '*'
      
env:
  DOCKER_USER_OPTION: '$UID:$GID'
  SCCACHE_GCS_BUCKET: 'composable-build-artefacts'
  RUSTC_WRAPPER: "/home/runner/.cargo/bin/sccache"
  SCCACHE_GCS_RW_MODE: "READ_WRITE"

jobs:
  build-and-publish:
    runs-on: 
        - self-hosted
        - linux
        - x64
        - sre
    strategy: 
      fail-fast: true

    steps:
    - name: cleanup 
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
  
    - name: Set env
      run: |
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1 )" >> $GITHUB_ENV
        make version

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: 🔨 Build and Upload Composable Binary
      id: client_release
      run: |
        .maintain/client_release.sh

    - name: Build wasm with srtool
      id: runtime_release
      run: |
        .maintain/runtime_release.sh
    
    - name: "✏️ Generate release changelog"
      id: changeloggen
      if: "${{ env.PICASSO_CHAIN }} = 1"
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }} 
    
    - name: Update Release Note
      if: "${{ env.PICASSO_CHAIN }} = 1"
      run: |
        mv /github/workspace/CHANGELOG.md release.md
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: release.md
        token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
    
    - name: Upload Compact Picasso wasm # TODO only upload wasm that has changed
      uses: svenstaro/upload-release-action@v2
      if: "${{ env.PICASSO_CHAIN }} = 1"
      with:
        repo_token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
        file: ./runtime/picasso/target/srtool/release/wbuild/picasso-runtime/picasso_runtime.compact.wasm
        asset_name: picasso_runtime.compact.wasm
        tag: ${{ github.ref }}
        overwrite: true
    
    - name: Upload Compact Dali wasm # TODO only upload wasm that has changed
      uses: svenstaro/upload-release-action@v2
      if: "${{ env.DALI_CHAIN }} = 1"
      with:
        repo_token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
        file: ./runtime/dali/target/srtool/release/wbuild/dali-runtime/dali_runtime.compact.wasm
        asset_name: dali_runtime.compact.wasm
        tag: ${{ github.ref }}
        overwrite: true
    
    - name: Upload Binary on Release # TODO Only upload binary if client files have changed
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
        file: target/release/composable
        asset_name: composable
        tag: ${{ github.ref }}
        overwrite: true


    
    
