name: CI Check

on:
  push:
    branches: "cleanup-ci"
  pull_request:
    branches:
      - main
      - develop
      - dali-chachacha
      - picasso
  workflow_dispatch:
jobs:
  check:
    runs-on:
      - self-hosted
      - linux
      - x64
      - sre
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
      - name: Check
        run: |
          rustup target add wasm32-unknown-unknown
          SKIP_WASM_BUILD=1 cargo check --all --benches
      - name: Benchmark
        run: |
          SKIP_WASM_BUILD=1 cargo check --features=runtime-benchmarks --workspace --release --exclude integration-tests
      - name: Benchmark Develop
        run: |
          SKIP_WASM_BUILD=1 cargo check --features=runtime-benchmarks,develop --workspace --release --exclude integration-tests
  linters:
    name: Linters
    runs-on:
      - self-hosted
      - linux
      - x64
      - sre
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - name: Cargo fmt
        run: |
          cargo +nightly fmt -- --check
      - name: Hadolint
      - uses: hadolint/hadolint-action@v2.8.0
        with:
          dockerfile: docker/Dockerfile
      - name: Cargo clippy
        run: |
          cargo +nightly clippy -- -D warnings
      - name: Cargo udeps
        env:
          UDEPS_VERSION: v0.1.24
        run: |
          curl -L -O "https://github.com/est31/cargo-udeps/releases/download/${UDEPS_VERSION}/cargo-udeps-${UDEPS_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          tar xzf "cargo-udeps-${UDEPS_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          cp "cargo-udeps-${UDEPS_VERSION}-x86_64-unknown-linux-gnu/cargo-udeps" ~/.cargo/bin/
          rm -r "cargo-udeps-${UDEPS_VERSION}-x86_64-unknown-linux-gnu.tar.gz" "cargo-udeps-${UDEPS_VERSION}-x86_64-unknown-linux-gnu"
          cargo udeps --version
          total_exit_code=0
          while IFS= read -r crate; do
            echo "=== $crate ==="
            (cd "$crate"; SKIP_WASM_BUILD=1 cargo +nightly udeps -q --all-targets) || total_exit_code=$?
            echo ""
          done < <(find . -name "Cargo.toml" -not -path "./polkadot-launch/*" -not -path "./target/*" -exec dirname '{}' \;)
          exit $total_exit_code
  test:
    name: Unit Test
    runs-on:
      - self-hosted
      - linux
      - x64
      - sre
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run Test
        run: |
          SKIP_WASM_BUILD=1 cargo test
          SKIP_WASM_BUILD=1 cargo clean -p picasso-runtime
          SKIP_WASM_BUILD=1 cargo clean -p composable
