name: "Community Release (Dali Chacha)"

on:
  push: 
    tags: 
      - '*'
    branches:
      - feature/workflow-test
      
env:
  DOCKER_USER_OPTION: '$UID:$GID'
  SCCACHE_GCS_BUCKET: 'composable-build-artefacts'
  RUSTC_WRAPPER: "/home/runner/.cargo/bin/sccache"
  SCCACHE_GCS_RW_MODE: "READ_WRITE"

jobs:
  build-and-publish:
    runs-on: 
        - self-hosted
        - linux
        - x64
        - sre
    strategy: 
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
  
    - name: Set env
      run: |
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1 )" >> $GITHUB_ENV
        make version

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: 🔨 Build Composable Artifacts
      run: |
        /home/runner/.cargo/bin/cargo build --release -p composable 
        /home/runner/.cargo/bin/cargo install --git https://github.com/chevdor/srtool-cli
        /home/runner/.cargo/bin/srtool build --package picasso-runtime --profile release --runtime-dir ./runtime/picasso

    - name: Archive build targets
      run: |
        tar -czvf composable-${{ env.RELEASE_VERSION }}.tar.gz target/release/composable
        tar -czvf picasso_runtime.compact.wasm-${RELEASE_VERSION}.tar.gz runtime/picasso/target/srtool/release/wbuild/picasso-runtime/picasso_runtime.compact.wasm
        gsutil cp *.tar.gz gs://composable-binaries/community-releases/${{ env.RELEASE_VERSION }}/ 

    - name: Upload Compact wasm
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
        file: ./runtime/picasso/target/srtool/release/wbuild/picasso-runtime/picasso_runtime.compact.wasm
        asset_name: picasso_runtime.compact.wasm
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload Compressed wasm
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
        file: ./runtime/picasso/target/srtool/release/wbuild/picasso-runtime/picasso_runtime.compact.compressed.wasm
        asset_name: picasso_runtime.compact.compressed.wasm
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload Binary on Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
        file: target/release/composable
        asset_name: composable-${{ env.RELEASE_VERSION }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "Composable Binary Runtime"
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  

    - name: Build Docker image
      run: make containerize-release 

    - name:  Docker push
      run: make push-release

  dali-chacha-client-release:
    needs: [build-and-publish]
    runs-on: 
      - self-hosted
      - linux
      - X64
      - ansible-runner

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Set env
      run: |
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1 )" >> $GITHUB_ENV

    - name: Run ansible playbook
      working-directory: "./.maintain/playbooks"
      run: |
        ansible-playbook -l _environment_testnet client-upgrade.yml -i gcp.yaml  --user runner -e 'ansible_python_interpreter=/usr/bin/python3'

