name: "Dali-chachacha Community Release"

on:
  push: 
    tags: 
      - 'dali-*'

env:
  CHAIN: "dali"

jobs:
  build-and-publish:
    runs-on: 
        - self-hosted
        - linux
        - x64
        - sre
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Set env
      run: |
<<<<<<< HEAD:.github/workflows/docker-release.yml
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1)" >> $GITHUB_ENV
=======
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^dali-[0-9]' | tail -1 )" >> $GITHUB_ENV
        make version
>>>>>>> 4af4e904f5eb0ea78f6ba91b6e7e1a4c9437f400:.github/workflows/dali-chachacha-release.yml

    - name: Build and Push Artifacts to gcloud
      run: |
        /home/runner/.cargo/bin/cargo build --release -p composable
        tar -czvf composable-${{ env.RELEASE_VERSION }}.tar.gz target/release/composable
        gsutil mv composable-${{ env.RELEASE_VERSION }}.tar.gz gs://composable-binaries/community-releases/dali/ 

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  

    - name: Build Docker image
      run: make containerize-release 
    - name:  Docker push
      run: make push-release
