name: "Community Release"

on:
  push:
    branches: "update-release"
    tags: 
      - '*'
env:
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_PROJECT_ID: "composable-ops-5568"
  REPO: "europe-central2-docker.pkg.dev/composable-ops-5568/composable-pkg"

jobs:
  build:
    runs-on: 
        - self-hosted
        - linux
        - x64
        - sre
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Set env
      run: |
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1)" >> $GITHUB_ENV

    # - name: Build and Push Artifacts to gcloud
    #   run: |
    #     /home/runner/.cargo/bin/cargo build --release -p composable
    #     gsutil cp target/release/composable gs://composable-binaries/releases/${{ env.RELEASE_VERSION }}/ 

  publish:
    runs-on: 
      - self-hosted
      - linux
      - x64
      - sre
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Set env
      run: |
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1)" >> $GITHUB_ENV

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: "349.0.0"
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Authenticate docker
      run: gcloud auth configure-docker europe-central2-docker.pkg.dev 

    - name: Build Docker image
      run: make containerize-release 
      
    - name:  Docker push
      run: make push-release
