name: "Picasso Community Release"

on:
  push: 
    tags: 
      - 'picasso-*'
env:
  CHAIN: "picasso"
  DOCKER_USER_OPTION: '$UID:$GID'

jobs:
  build-and-publish:
    runs-on: 
        - self-hosted
        - linux
        - x64
        - sre
    strategy:
      matrix:
        chain: ["dali-chachacha", "picasso"]
    
    steps:
    - name: cleanup 
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
        ref: picasso

    - name: Set env
      run: |
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^picasso-[0-9]' | tail -1 )" >> $GITHUB_ENV
        make version

    - name: FiletoUpload
      run: |
        echo "Test Release" > release.md
    
    - name: Upload Binary on Release
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
        file: release.md
        asset_name: release.md
        #file: target/release/composable
        #asset_name: composable-${{ env.RELEASE_VERSION }}
        tag: ${{ github.ref }}
        overwrite: true
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: release.md
        token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}

    