name: "Picasso Community Release"

on:
  push: 
    tags: 
      - 'picasso-*'
env:
  CHAIN: "picasso"
  DOCKER_USER_OPTION: '$UID:$GID'

jobs:
  build-and-publish:
    runs-on: 
        - self-hosted
        - linux
        - x64
        - sre
    strategy:
      matrix:
        chain: ["dali-chachacha", "picasso"]
    
    steps:
    - name: cleanup 
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
        ref: picasso

    - name: Set env
      run: |
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^picasso-[0-9]' | tail -1 )" >> $GITHUB_ENV
        make version

    - name: Build and Push Artifacts to gcloud
      run: |
        /home/runner/.cargo/bin/cargo build --release --bins
        tar -czvf composable-${{ env.RELEASE_VERSION }}.tar.gz target/release/composable
        tar -czvf parachain-utils-${RELEASE_VERSION}.tar.gz target/release/parachain-utils

    - name: Build with srtool
      run: |
        /home/runner/.cargo/bin/cargo install --git https://github.com/chevdor/srtool-cli
        /home/runner/.cargo/bin/srtool build --package picasso-runtime --profile release --runtime-dir ./runtime/picasso > srtool.out
        tl=$(sed -n '$=' srtool.out)
        itl=$(sed -n '/Package/=' srtool.out)
        echo $itl, $tl
        echo "outsrtool=$(sed -n "$itl,$tl"p srtool.out)"
        echo  $outsrtool
    
    - name: Get wasm info
      run: |
        cargo install --locked --git https://github.com/chevdor/subwasm --tag v0.16.1
        subwasm info --input ./runtime/picasso/target/srtool/release/wbuild/picasso-runtime/picasso_runtime.compact.wasm

    #- name: Build with srtool
    #  uses: chevdor/srtool-actions@v0.2.0
    #  with:
    #      chain: ${{ matrix.chain }}
    #      package: picasso-runtime
    #      runtime_dir: ./runtime/picasso
          
    #- name: Srtool build Summary
    #  run: |
    #     echo "VERSION=${{ steps.srtool_build.outputs.version }}"
    #     echo "PROPOSAL=${{ steps.srtool_build.outputs.proposal_hash }}"
    #     echo "BLAKE2_256=${{ steps.srtool_build.outputs.blake2_256 }}"
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 

    - name: Build Docker image
      run: make containerize-release 
    - name:  Docker push
      run: make push-release

    - name: Upload Compact wasm
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
        file: ./runtime/picasso/target/srtool/release/wbuild/picasso-runtime/picasso_runtime.compact.wasm
        asset_name: picasso_runtime.compact.wasm
        tag: ${{ github.ref }}
        overwrite: true
    
    - name: Upload Binary on Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
        file: target/release/composable
        asset_name: composable-${{ env.RELEASE_VERSION }}
        tag: ${{ github.ref }}
        overwrite: true
        body: |
          Completed wasm build Information