name: "Publish Release"

on:
  workflow_dispatch:
    inputs:
      chain:
        description: Chain Runtime (default = karura)    
        required: true
        default: picasso
        type: choice
        options:
            - picasso
            - dali-chachacha
            - composable
  push: 
    branches:
      - test-release-note
    tags: 
      - '*'

env:
  DOCKER_USER_OPTION: '$UID:$GID'
  SCCACHE_GCS_BUCKET: 'composable-build-artefacts'
  RUSTC_WRAPPER: "/home/runner/.cargo/bin/sccache"
  SCCACHE_GCS_RW_MODE: "READ_WRITE"

jobs:
  build-and-publish:
    runs-on: 
      - self-hosted
      - linux
      - x64
      - sre
    strategy:
      fail-fast: true
      matrix:
        chain: ["picasso", "dali"]
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Set env
      run: |
        echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1 )" >> $GITHUB_ENV
        make version

    - name: Srtool build
      id: srtool_build
      uses: chevdor/srtool-actions@v0.3.0
      with:
        chain: ${{ matrix.chain }}
        runtime_dir: runtime//${{ matrix.chain }}

    - name: Build Summary
      run: |
        echo '${{ steps.srtool_build.outputs.json }}' | jq . > ${{ github.event.inputs.chain }}-srtool-digest.json
        cat ${{ github.event.inputs.chain }}-srtool-digest.json
        echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"

    - name: Install subwasm ${{ env.SUBWASM_VERSION }}
      run: |
        wget https://github.com/chevdor/subwasm/releases/download/v${{ env.SUBWASM_VERSION }}/subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
        sudo dpkg -i subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
        subwasm --version

    - name: Extract metadata
      run: |
        subwasm  --json info ${{ steps.srtool_build.outputs.wasm }} > ${{ github.event.inputs.chain }}-info.json
        subwasm info ${{ steps.srtool_build.outputs.wasm }} > ${{ github.event.inputs.chain }}-info.txt
        cat ${{ github.event.inputs.chain }}-info.txt
        subwasm  --json info ${{ steps.srtool_build.outputs.wasm_compressed }} > ${{ github.event.inputs.chain }}-subwam-info.json
        subwasm info ${{ steps.srtool_build.outputs.wasm_compressed }} > ${{ github.event.inputs.chain }}-subwam-info.txt
        cat ${{ github.event.inputs.chain }}-subwam-info.txt

    - name: Check the metadata diff
      run: |
        subwasm diff ${{ steps.srtool_build.outputs.wasm }} --chain-b ${{ github.event.inputs.chain }} | tee ${{ github.event.inputs.chain }}-diff.txt
    
    
