name: Release Drafter
on:
  push:
    branches:
      - stable-release
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}

      - name: Set env
        run: |
          echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1)" >> $GITHUB_ENV
          make version

