name: Release Drafter
on:
  push:
    branches:
      - releases
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
          WITH_V: true

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}

    
