name: Release Drafter
on:
  push:
    branches:
      - test-upload-from-output
jobs:
  build-and-publish:
    runs-on: 
        - self-hosted
        - linux
        - x64
        - sre
    strategy: 
      fail-fast: true
    steps:
    - name: Clean up
      continue-on-error: true
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
        docker system prune --force --all --volumes

    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
  
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: 🔨 Install srtool
      id: client_release
      run: |
        cargo install --git https://github.com/chevdor/srtool-cli
        cargo install --locked --git https://github.com/chevdor/subwasm --tag v0.16.1

    - name: 🔨 Build and Upload Composable Binary
      id: client_release
      run: |
        .maintain/client_release.sh

    - name: Build wasm with srtool
      id: runtime_release
      run: |
        .maintain/runtime_release.sh

    - uses: release-drafter/release-drafter@v5
      id: release_drafter
      env:
        GITHUB_TOKEN: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}

    - name: Upload Compact Picasso wasm
      id: upload-release-asset 
      if: env.picasso_wasm == 1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release_drafter.outputs.upload_url }} 
        asset_path: ./runtime/picasso/target/srtool/release/wbuild/picasso-runtime/picasso_runtime.compact.wasm
        asset_name: picasso_runtime.compact.wasm

