name: Release Drafter
on:
  push:
    branches:
      - releases
      - test-release

env:
  COMPOSABLE_GITHUB_TOKEN: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}

jobs:
  build-and-publish:
    runs-on: 
        - self-hosted
        - linux
        - x64
        - sre
    strategy: 
      fail-fast: true
      matrix: 
        runtime: [picasso]
    steps:
    - name: Clean up
      continue-on-error: true
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
        docker system prune --force --all --volumes

    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
  
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install srtool
      run: |
        cargo install --git https://github.com/chevdor/srtool-cli
        cargo install --locked --git https://github.com/chevdor/subwasm --tag v0.16.1

    - name: Run runtime release
      env:
        COMPOSABLE_GITHUB_TOKEN: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }} 
      id: runtime_release
      run: |
        export COMPOSABLE_GITHUB_TOKEN=${{ secrets.COMPOSABLE_GITHUB_TOKEN }} 
        .maintain/runtime_release.sh

    - uses: release-drafter/release-drafter@v5
      id: release_drafter
      with:
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Get Body
      env:
        GITHUB_TOKEN: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
      run: |
        cd scripts/github && npm install
        echo "${{ steps.release_drafter.outputs.body }}" >> $GITHUB_WORKSPACE/release.md
        npm run update-release-body -- --id=${{ steps.release_drafter.outputs.id  }} --repo=composableFi/composable --body="$GITHUB_WORKSPACE/release.md"
        cd $GITHUB_WORKSPACE

    - name: Upload Compact ${{ matrix.runtime }} wasm
      id: upload-release-asset 
      if: env.${{ matrix.runtime }}_wasm == 1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.COMPOSABLE_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release_drafter.outputs.upload_url }} 
        asset_path: ./runtime/${{ matrix.runtime }}/target/srtool/release/wbuild/${{ matrix.runtime }}-runtime/${{ matrix.runtime }}_runtime.compact.wasm
        asset_name: ${{ matrix.runtime }}_runtime.compact.wasm
        asset_content_type: application/octet-stream

    - name: 🔨 Build and Upload Composable Binary
      run: |
        .maintain/client_release.sh

