name: Check Runtime
on:
  push:
    branches:
      - release-*
      - main
  pull_request:
    branches:
      - release-*
      - main
jobs:
  check-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Check for runtime changes
        working-directory: "./.maintain/"
        run: |
          ./check_runtime.sh

      # - name: Simnode integration test
      #   run : |
      #     YDATE=$(date -d yesterday +'%m-%d-%Y')
      #     FILENAME=cl-1-$YDATE.zip
      #     GS_BUCKET="picasso-data-store"
      #     sudo gsutil cp gs://$GS_BUCKET/$FILENAME .
      #     sudo unzip -o $FILENAME -d  /tmp/db
      #     sudo wget simmode
      #     simnode --chain=$2 --base-path=/tmp/db --pruning=archive --execution=wasm

