name: Runtime Release
on:
  push:
    branches:
      - 'release/**'

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: <instance-name>
  GCE_INSTANCE_ZONE: us-west4-b 

jobs:
  docker-build:
    runs-on: 
      - self-hosted
      - linux
      - x64
      - sre
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Set env
        run: echo "RELEASE_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Build and Push Artifacts to gcloud
        run: |
          /home/runner/.cargo/bin/cargo build --release -p composable
          /home/runner/.cargo/bin/cargo build --release -p parachain-utils
          /home/runner/.cargo/bin/cargo build --release -p rotate-keys
          gsutil cp target/release/composable gs://composable-binaries/releases/client/v0.1.0/ 
          gsutil cp target/release/parachain-utils gs://composable-binaries/releases/client/v0.1.0/
          gsutil cp target/release/rotate-keys gs://composable-binaries/releases/client/v0.1.0/  
          gsutil cp target/release/wbuild/picasso-runtime/picasso_runtime.compact.wasm gs://composable-binaries/releases/client/v0.1.0/ 


