name: Run Simnode
on:
  pull_request:
    branches:
      - releases
      - main
env:
  BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
jobs:
  simnode:
    runs-on: 
      - self-hosted
      - linux
      - x64
      - sre
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: main

      - name: Check for runtime changes
        id: check_runtime
        run: .maintain/check_runtime.sh

      - name: Echo output
        run: |
          echo ${{ env.BASE_BRANCH }}
          echo ${{ env.RUNTIME_CHECK }}

      - name: Run Simnode
        if: "$${{ env.RUNTIME_CHECK }} == 1"
        id: run_simnode
        run: .maintain/run_simnode.sh
