name: Run Simnode
on:
  pull_request:
    branches:
      - releases
      - main
jobs:
  simnode:
    runs-on:
      - self-hosted
      - linux
      - x64
      - sre
    if: github.event.pull_request.draft == false
    steps:
      - name: Clean up
        continue-on-error: true
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
          docker system prune --force --all --volumes

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}  

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - name: Running on a pull request branch.
        if: steps.branch-name.outputs.is_default == 'false'
        run: |
          echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"

      # - name: Check for runtime changes
      #   id: check_runtime
      #   env:
      #     BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
      #     GITHUB_REF: ${{ github.ref_name }}

      #   run: .maintain/check_runtime.sh

      # - name: Run Simnode
      #   env:
      #     BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
      #     GITHUB_REF: ${{ github.ref_name	 }}

      #   if: env.RUNTIME_CHECK == 1
      #   id: run_simnode
      #   run: .maintain/run_simnode.sh
